version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog-temp
    volumes:
      - /var/lib/docker/volume/velex-back/_data:/var/lib/postgresql/data
    ports:
      - 5432:5432